baseURL = "/"
languageCode = "en-us"
title = "Broken Pieces"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
    site_logo = "/img/brokenpieces-logo-transparent.webp"

    # Custom CSS for fonts
    custom_css = ["css/custom.css"]

    # Make sure that only news gets displayed on the front page, not music and lyrics and the blog
    mainSections = ["news"]

    instagram = "https://www.instagram.com/broken_piecesofficial1/"
    github = "https://github.com/brokenpiecesofficial/"
    twitter = "https://twitter.com/BrokenPiecesKC"
    youtube = "https://www.youtube.com/channel/UChceKMfccC_X_sOUBpblSQg"

[privacy]
    [privacy.twitter]
        enableDNT = true
    [privacy.youtube]
        privacyEnhanced = true
