baseURL = "/"
languageCode = "en-us"
title = "Broken Pieces"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
    site_logo = "/img/brokenpieces-logo-transparent.webp"

    # Make the image that appears when some sites show info about a page the logo for every page
    images = ["/img/brokenpieces-logo-transparent.webp"]

    # Custom CSS for fonts
    custom_css = ["css/custom.css"]

    # Make sure that only news gets displayed on the front page, not music and lyrics and the blog
    mainSections = ["news"]

    # Social links (show up in header and footer):
    instagram = "https://www.instagram.com/brokenpieces_official/"
    github = "https://github.com/brokenpiecesofficial/"
    twitter = "https://twitter.com/BrokenPiecesKC"
    youtube = "https://www.youtube.com/channel/UChceKMfccC_X_sOUBpblSQg"
    facebook = "https://www.facebook.com/Broken-Pieces-103902529133607"

[[menu.main]]
    identifier = "listen"
    name = "Listen to us!"
    url = "https://soundcloud.com/brokenpieces_official"
    weight = 1

[privacy]
    [privacy.twitter]
        enableDNT = true
    [privacy.youtube]
        privacyEnhanced = true
