name: Build and push to production

on:
  # Run on tag/branch creation
  #create:
  
  #schedule:
  # - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Build
      uses: jakejarvis/hugo-build-action@master
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: ${{ secrets.FTP_USER }}
        server: ${{ secrets.FTP_URL }}
        ssh_private_key: ${{ secrets.FTP_KEY }}
        local_path: "./public/*"
        remote_path: ${{ secrets.SERVER_DIR }}
