name: Build and push to production

on:
  # Run on tag/branch creation
  create:
  
  schedule:
   - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: jakejarvis/hugo-build-action@master
    - name: Deploy with SFTP
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        # Literally just using a secret for this first one so I can change it without having to commit again
        server: ${{ secrets.FTP_URL }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: ./public/
        server-dir: ${{ secrets.SERVER_DIR }}
        log-level: standard
